name: Test and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: |
          npm install
          npm install -g @salesforce/cli
      - name: Run Unit Tests
        run: npm test
      - name: Release package
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
